
spring.application.name=Spring_Security_JWT

server.port=7878

# 🔐 SSL Configuration
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=123456
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=myapp

# Disable DB auto config (your existing)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# Logging (your existing)
logging.level.com.Spring_Security_JWT.*=debug
logging.file.name=./STSLOGS/JWTSPRING/DEMO/practical.log
logging.logback.rollingpolicy.max-file-size=20MB